apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitea
  labels:
    project: gitea
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: gitea
    fsType: ext4
